<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>nl.hauntedmc.dataprovider</groupId>
        <artifactId>dataprovider-parent</artifactId>
        <version>${revision}</version>
    </parent>
    <artifactId>dataprovider-standalone</artifactId>
    <name>DataProvider Standalone Host</name>
    <dependencies>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>dataprovider-core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
